services:
  - type: web
    name: sistema-aprendizaje-autismo
    env: python
    rootDir: PROYECTO SISTEMAS
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: SECRET_KEY
        generateValue: true 